/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    vehicles: Vehicle;
    services: Service;
    'service-categories': ServiceCategory;
    'service-options': ServiceOption;
    orders: Order;
    'customer-tiers': CustomerTier;
    media: Media;
    'whatsapp-messages': WhatsappMessage;
    'whatsapp-templates': WhatsappTemplate;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    'service-options': ServiceOptionsSelect<false> | ServiceOptionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'customer-tiers': CustomerTiersSelect<false> | CustomerTiersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'whatsapp-messages': WhatsappMessagesSelect<false> | WhatsappMessagesSelect<true>;
    'whatsapp-templates': WhatsappTemplatesSelect<false> | WhatsappTemplatesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'staff' | 'customer';
  whatsappNumber?: string | null;
  /**
   * Whether the WhatsApp number has been verified through conversation
   */
  whatsappVerified?: boolean | null;
  /**
   * User consent for receiving WhatsApp notifications
   */
  whatsappOptIn?: boolean | null;
  /**
   * Last time customer initiated WhatsApp contact (for 24h messaging window)
   */
  lastWhatsappContact?: string | null;
  /**
   * Gupshup conversation identifier for this user
   */
  whatsappConversationId?: string | null;
  customerTier?: (string | null) | CustomerTier;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-tiers".
 */
export interface CustomerTier {
  id: string;
  /**
   * Name of the customer tier (e.g., "Standard", "Fleet", "VIP Member")
   */
  tierName: string;
  /**
   * Description of the benefits and features of this tier
   */
  description?: string | null;
  /**
   * Default queue priority for customers in this tier
   */
  defaultQueue: 'regular' | 'vip' | 'remnant';
  /**
   * General discount percentage for this tier (0-100)
   */
  discountPercentage?: number | null;
  /**
   * Specific pricing overrides for individual services
   */
  pricingOverrides?:
    | {
        service: string | Service;
        overriddenPrice: number;
        /**
         * Alternative to fixed price - percentage discount
         */
        discountPercentage?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * List of benefits for this tier
   */
  benefits?:
    | {
        benefit: string;
        /**
         * Lucide icon name for this benefit
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Color theme for this tier in the UI
   */
  color?: ('blue' | 'purple' | 'green' | 'pink' | 'orange' | 'gold' | 'silver') | null;
  /**
   * Minimum total spend required to qualify for this tier
   */
  minimumSpend?: number | null;
  /**
   * Automatically upgrade customers who meet the minimum spend
   */
  autoUpgrade?: boolean | null;
  /**
   * Order in which tiers appear (lower numbers first)
   */
  sortOrder?: number | null;
  /**
   * Whether this tier is available for assignment
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Name of the service (e.g., "Basic Wash", "Premium Detail")
   */
  name: string;
  /**
   * Detailed description of what this service includes
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which category this service belongs to
   */
  category: string | ServiceCategory;
  /**
   * Base price for this service (in your local currency)
   */
  basePrice: number;
  /**
   * Different pricing for different vehicle types (overrides base price)
   */
  vehicleTypePricing?:
    | {
        vehicleType: 'sedan' | 'mpv_van' | 'large_pickup' | 'regular_bike' | 'heavy_bike' | 'very_heavy_bike';
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Individual steps that make up this service
   */
  steps?:
    | {
        stepName: string;
        estimatedMinutes: number;
        description?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Service options that can be added to this service
   */
  compatibleOptions?: (string | ServiceOption)[] | null;
  /**
   * Total estimated time for this service
   */
  estimatedMinutes: number;
  /**
   * Image representing this service
   */
  image?: (string | null) | Media;
  /**
   * Lucide icon name for this service
   */
  icon?: string | null;
  /**
   * Mark as popular to highlight in the UI
   */
  isPopular?: boolean | null;
  /**
   * Order in which services appear (lower numbers first)
   */
  sortOrder?: number | null;
  /**
   * Whether this service is available for booking
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: string;
  /**
   * Name of the service category (e.g., "Exterior Wash", "Interior Detailing")
   */
  name: string;
  /**
   * Brief description of what this category includes
   */
  description?: string | null;
  /**
   * Lucide icon name for the category (e.g., "car", "sparkles")
   */
  icon?: string | null;
  /**
   * Color theme for this category in the UI
   */
  color?: ('blue' | 'purple' | 'green' | 'pink' | 'orange') | null;
  /**
   * Order in which categories appear (lower numbers first)
   */
  sortOrder?: number | null;
  /**
   * Whether this category is available for selection
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-options".
 */
export interface ServiceOption {
  id: string;
  /**
   * Name of the service option (e.g., "Tire Shine", "Wax Coating")
   */
  name: string;
  /**
   * Detailed description of what this option includes
   */
  description?: string | null;
  /**
   * Additional cost for this option (in your local currency)
   */
  additionalPrice: number;
  /**
   * Which service category this option belongs to
   */
  category?: (string | null) | ServiceCategory;
  /**
   * Vehicle types this option can be applied to (leave empty for all)
   */
  applicableVehicleTypes?:
    | ('sedan' | 'mpv_van' | 'large_pickup' | 'regular_bike' | 'heavy_bike' | 'very_heavy_bike')[]
    | null;
  /**
   * Additional time this option adds to the service
   */
  estimatedMinutes?: number | null;
  /**
   * Lucide icon name for this option
   */
  icon?: string | null;
  /**
   * Mark as popular to highlight in the UI
   */
  isPopular?: boolean | null;
  /**
   * Order in which options appear (lower numbers first)
   */
  sortOrder?: number | null;
  /**
   * Whether this option is available for selection
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  /**
   * Optional caption for the image
   */
  caption?: string | null;
  /**
   * Category to help organize media files
   */
  category?: ('vehicle' | 'service' | 'before_after' | 'general') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  /**
   * Vehicle license plate number
   */
  licensePlate: string;
  /**
   * Photo of the vehicle for AI classification
   */
  image?: (string | null) | Media;
  /**
   * Vehicle type determined by AI or manually selected
   */
  vehicleType: 'sedan' | 'mpv_van' | 'large_pickup' | 'regular_bike' | 'heavy_bike' | 'very_heavy_bike';
  /**
   * Customer who owns this vehicle
   */
  owner: string | User;
  /**
   * Vehicle manufacturer (e.g., Toyota, Honda)
   */
  make?: string | null;
  /**
   * Vehicle model (e.g., Camry, Civic)
   */
  model?: string | null;
  /**
   * Manufacturing year
   */
  year?: number | null;
  /**
   * Primary vehicle color
   */
  color?: string | null;
  /**
   * Additional notes about the vehicle
   */
  notes?: string | null;
  /**
   * Confidence score from AI classification (0-1)
   */
  aiClassificationConfidence?: number | null;
  /**
   * Whether this vehicle is actively used by the customer
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Auto-generated unique order identifier
   */
  orderID: string;
  /**
   * Current stage of the order in the WhatsApp workflow
   */
  orderStage: 'empty' | 'initiated' | 'open' | 'billed' | 'paid';
  /**
   * Whether this order has been linked to a WhatsApp conversation
   */
  whatsappLinked?: boolean | null;
  /**
   * WhatsApp number of the customer who initiated this order
   */
  whatsappNumber?: string | null;
  /**
   * Whether a QR code has been generated for this order
   */
  qrCodeGenerated?: boolean | null;
  /**
   * When the customer scanned the QR code
   */
  qrCodeScannedAt?: string | null;
  /**
   * When the vehicle information was captured
   */
  vehicleCapturedAt?: string | null;
  /**
   * When AI processing of vehicle information was completed
   */
  aiProcessedAt?: string | null;
  /**
   * When the payment link was sent via WhatsApp
   */
  paymentLinkSentAt?: string | null;
  /**
   * Customer who placed this order
   */
  customer?: (string | null) | User;
  /**
   * Vehicle being serviced
   */
  vehicle?: (string | null) | Vehicle;
  /**
   * Services and options included in this order
   */
  servicesRendered?:
    | {
        service: string | Service;
        selectedOptions?: (string | ServiceOption)[] | null;
        /**
         * Final price for this service (after tier discounts)
         */
        servicePrice: number;
        /**
         * Total price for selected options
         */
        optionsPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total order amount including all services and options
   */
  totalAmount: number;
  /**
   * Total discount applied to this order
   */
  discountAmount?: number | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded' | 'cash';
  /**
   * Transaction ID from Fiuu payment gateway
   */
  fiuuTransactionId?: string | null;
  queue: 'regular' | 'vip' | 'remnant';
  /**
   * Progress tracking for each step of the service
   */
  jobStatus?:
    | {
        stepName: string;
        status: 'pending' | 'in_progress' | 'completed' | 'skipped';
        completedBy?: (string | null) | User;
        timestamp?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  overallStatus: 'pending' | 'in_progress' | 'completed' | 'ready' | 'picked_up' | 'cancelled';
  /**
   * When the service is expected to be completed
   */
  estimatedCompletionTime?: string | null;
  /**
   * When the service was actually completed
   */
  actualCompletionTime?: string | null;
  /**
   * Special requests or notes from the customer
   */
  customerNotes?: string | null;
  /**
   * Internal notes for staff
   */
  staffNotes?: string | null;
  /**
   * Staff member who created this order
   */
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * WhatsApp message history and conversation tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-messages".
 */
export interface WhatsappMessage {
  id: string;
  /**
   * User associated with this message
   */
  user?: (string | null) | User;
  /**
   * Order associated with this message conversation
   */
  order?: (string | null) | Order;
  /**
   * Unique message identifier from Gupshup
   */
  messageId: string;
  /**
   * Gupshup conversation identifier
   */
  conversationId?: string | null;
  /**
   * WhatsApp number that sent/received this message
   */
  whatsappNumber: string;
  /**
   * Message direction relative to our system
   */
  direction: 'inbound' | 'outbound';
  /**
   * Type of WhatsApp message
   */
  messageType: 'text' | 'template' | 'media' | 'interactive';
  /**
   * The actual message content
   */
  content: string;
  /**
   * Name of the template used (for template messages)
   */
  templateName?: string | null;
  /**
   * Delivery status of the message
   */
  status: 'sent' | 'delivered' | 'read' | 'failed' | 'received';
  /**
   * When the message was sent/received
   */
  timestamp: string;
  /**
   * Additional message metadata from Gupshup
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error details if message failed
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * WhatsApp message templates for automated communications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-templates".
 */
export interface WhatsappTemplate {
  id: string;
  /**
   * Internal name for this template
   */
  name: string;
  /**
   * Template ID from Gupshup dashboard
   */
  templateId: string;
  /**
   * Category of this template for organization
   */
  category:
    | 'order_initiated'
    | 'vehicle_captured'
    | 'services_added'
    | 'payment_request'
    | 'completion'
    | 'welcome'
    | 'status_update'
    | 'error'
    | 'promotional';
  /**
   * Template content with variable placeholders (e.g., {{orderID}})
   */
  content: string;
  /**
   * Variables that can be substituted in this template
   */
  variables?:
    | {
        /**
         * Variable name without curly braces (e.g., orderID)
         */
        variable: string;
        /**
         * Description of what this variable represents
         */
        description?: string | null;
        /**
         * Whether this variable is required for the template
         */
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * WhatsApp approval status for this template
   */
  approvalStatus: 'pending' | 'approved' | 'rejected' | 'in_review';
  /**
   * Whether this template is active and can be used
   */
  isActive?: boolean | null;
  /**
   * Language of this template
   */
  language: 'en' | 'ms' | 'zh' | 'ta';
  /**
   * Number of times this template has been used
   */
  usageCount?: number | null;
  /**
   * When this template was last used
   */
  lastUsed?: string | null;
  /**
   * Internal notes about this template
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: string | ServiceCategory;
      } | null)
    | ({
        relationTo: 'service-options';
        value: string | ServiceOption;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'customer-tiers';
        value: string | CustomerTier;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'whatsapp-messages';
        value: string | WhatsappMessage;
      } | null)
    | ({
        relationTo: 'whatsapp-templates';
        value: string | WhatsappTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  whatsappNumber?: T;
  whatsappVerified?: T;
  whatsappOptIn?: T;
  lastWhatsappContact?: T;
  whatsappConversationId?: T;
  customerTier?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  licensePlate?: T;
  image?: T;
  vehicleType?: T;
  owner?: T;
  make?: T;
  model?: T;
  year?: T;
  color?: T;
  notes?: T;
  aiClassificationConfidence?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  basePrice?: T;
  vehicleTypePricing?:
    | T
    | {
        vehicleType?: T;
        price?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        stepName?: T;
        estimatedMinutes?: T;
        description?: T;
        sortOrder?: T;
        id?: T;
      };
  compatibleOptions?: T;
  estimatedMinutes?: T;
  image?: T;
  icon?: T;
  isPopular?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-options_select".
 */
export interface ServiceOptionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  additionalPrice?: T;
  category?: T;
  applicableVehicleTypes?: T;
  estimatedMinutes?: T;
  icon?: T;
  isPopular?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderID?: T;
  orderStage?: T;
  whatsappLinked?: T;
  whatsappNumber?: T;
  qrCodeGenerated?: T;
  qrCodeScannedAt?: T;
  vehicleCapturedAt?: T;
  aiProcessedAt?: T;
  paymentLinkSentAt?: T;
  customer?: T;
  vehicle?: T;
  servicesRendered?:
    | T
    | {
        service?: T;
        selectedOptions?: T;
        servicePrice?: T;
        optionsPrice?: T;
        id?: T;
      };
  totalAmount?: T;
  discountAmount?: T;
  paymentStatus?: T;
  fiuuTransactionId?: T;
  queue?: T;
  jobStatus?:
    | T
    | {
        stepName?: T;
        status?: T;
        completedBy?: T;
        timestamp?: T;
        notes?: T;
        id?: T;
      };
  overallStatus?: T;
  estimatedCompletionTime?: T;
  actualCompletionTime?: T;
  customerNotes?: T;
  staffNotes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-tiers_select".
 */
export interface CustomerTiersSelect<T extends boolean = true> {
  tierName?: T;
  description?: T;
  defaultQueue?: T;
  discountPercentage?: T;
  pricingOverrides?:
    | T
    | {
        service?: T;
        overriddenPrice?: T;
        discountPercentage?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        icon?: T;
        id?: T;
      };
  color?: T;
  minimumSpend?: T;
  autoUpgrade?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-messages_select".
 */
export interface WhatsappMessagesSelect<T extends boolean = true> {
  user?: T;
  order?: T;
  messageId?: T;
  conversationId?: T;
  whatsappNumber?: T;
  direction?: T;
  messageType?: T;
  content?: T;
  templateName?: T;
  status?: T;
  timestamp?: T;
  metadata?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-templates_select".
 */
export interface WhatsappTemplatesSelect<T extends boolean = true> {
  name?: T;
  templateId?: T;
  category?: T;
  content?: T;
  variables?:
    | T
    | {
        variable?: T;
        description?: T;
        required?: T;
        id?: T;
      };
  approvalStatus?: T;
  isActive?: T;
  language?: T;
  usageCount?: T;
  lastUsed?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}